name = "ssagov"
type = "webpack"
account_id = "41c979ec0c01c61c270c515c9b08fc59"
workers_dev = true
webpack_config = "node_modules/flareact/webpack"
kv_namespaces = [{ binding = "KV_STATUS_PAGE", id = "f86c079fe1394185bde2279a5d299f09" }]

[triggers]
crons = ["*/3 * * * *"]

[site]
bucket = "out"
entry-point = "./"

[env.production]
kv_namespaces = [{ binding = "KV_STATUS_PAGE", id = "f86c079fe1394185bde2279a5d299f09" }]
